services:
  backend:
    build: .
    container_name: 100-khana-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - 100-khana-network
  db:
    container_name: 100-khana-db
    image: postgres:14.19-trixie
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 100-khana-network

volumes:
  postgres_data:
networks:
  100-khana-network: